#!/bin/sh

. wmutils.conf

read DX DY DW DH <<< $(geo-disp $(current-disp $CUR))

X=0
Y=0

case $1 in
    tr) X=$((DX + DW - W - BW*2)) ;;
    bl) Y=$((DY + DH - H - BW*2)) ;;
    br) X=$((DX + DW - W - BW*2))
        Y=$((DY + DH - H - BW*2)) ;;
    md) X=$((DX + DW/2 - W/2 - BW))
        Y=$((DY + DH/2 - H/2 - BW));;
esac

wtp $X $Y $W $H $CUR
