#!/bin/sh

# x-event listener, meant to read from the output of `wew`
# based on z3bra's yawee script
# depends on: wew, focus, should-focus, corner

handle_creation() {
    corner md $1
}

handle_map() {
    if should-focus $1 ; then
        focus $wid
    fi
}

while IFS=: read ev wid; do
    case $ev in
        # entering window (focus follow mouse)
        7) wattr o $wid || focus $wid ;;

        # window creation
        16) wattr o $wid ||
                  handle_creation $wid ;;

        # focus next window when deleting focused window
        18) wattr $(pfw) || focus prev 2>/dev/null;;

        # mapping requests
        19) wattr o $wid ||
                  handle_map $wid ;;

    esac
done
