#!/bin/sh

# x-event listener, meant to read from the output of `wew`
# based on z3bra's yawee script
# depends on: wew, focus, should-focus, corner, wroot (for blurring bg)

handle_map() {
    if should-focus $1 ; then
        focus $wid
        wig -s $wid
        test "$(lsw | wc -l)" -ne 0 && wroot -b
    fi
}

while IFS=: read ev wid; do
    case $ev in
        # entering window (focus follow mouse)
        7) wattr o $wid || focus $wid ;;
        # window creation
        16) wattr o $wid || corner md $wid
            test "$(lsw | wc -l)" -ne 0 && wroot -b ;;
        # focus next window when deleting focused window
        18) wattr $(pfw) || focus prev 2>/dev/null
            test "$(lsw | wc -l)" -eq 0 && wroot -u ;;
        # mapping requests (focus newly created windows)
        19) wattr o $wid || handle_map $wid ;;
    esac
done
