#!/bin/sh
#
# depends: lemonbar, wattr, wmutils.conf

. wmutils.conf

default_geometry() {
    # get screen size
    x=$(wattr w `lsw -r`)
    y=$(wattr h `lsw -r`)

    height=200

    offy=$((SH - SH/2 - height/2))
    offx=0

    echo "${x}x${height}+${offx}+${offy}"
}

test "$#" -lt 1 && exit 1

while getopts "d:g:h" opt; do
    case $opt in
        d) n=$OPTARG & shift 2 ;;
        g) g=$OPTARG & shift 2  ;;
        h) usage; exit 0 ;;
        *) usage; exit 1 ;;
    esac
done

g=${g:-$(default_geometry)}
n=${n:-3}

(echo "%{c}$@"; sleep $n) | lemonbar -f "$MONOTTF-24" -g $g -B "#$(xbg)" -F "#$(xfg)"
